#server:
#  port: 8081
#
#spring:
#  #数据源配置
#  datasource:
#    url: jdbc:mysql://localhost:3306/ssmDemo?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: hkbt1234
#    driver-class-name: com.mysql.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#
##端口号
server.port=8080
##数据库配置
spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
spring.datasource.url=jdbc:mysql://localhost:3306/ssmDemo
spring.datasource.username=root
spring.datasource.password=hkbt1234
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.max-idle=10
spring.datasource.max-wait=10000
spring.datasource.min-idle=5
spring.datasource.initial-size=5
##mybatis-plus mapper xml 文件地址
mybatis-plus.mapper-locations=classpath:/mapper/*Mapper.xml
mybatis-plus.typeAliasesPackage=com.yjl.demo.base.entity
